// src/app/ui/game-hud.component.ts
import { Component, Input } from '@angular/core';
import { Haptics, ImpactStyle } from '@capacitor/haptics';
import type { InputStateService } from '../state/input-state.service';
import type { InputState } from '../types/game';

@Component({
  selector: 'app-game-hud',
  templateUrl: './game-hud.component.html',
  styleUrls: ['./game-hud.component.scss'],
})
export class GameHudComponent {
  @Input() score = 0;
  @Input() biome = 0;
  @Input() dialogue: { speaker: string; text: string } | null = null;

  readonly biomeNames = ['SHIBUYA', 'ROPPONGI', 'AKIHABARA', 'SHINJUKU'];

  constructor(private readonly inputState: InputStateService) {}

  async handleTouchStart(key: keyof InputState): Promise<void> {
    this.inputState.setKey(key, true);
    try {
      await Haptics.impact({ style: ImpactStyle.Light });
    } catch {
      // ignore
    }
  }

  handleTouchEnd(key: keyof InputState): void {
    this.inputState.setKey(key, false);
  }
}

<div class="game-hud">
  <div class="top-bar">
    <div class="hud-box">
      <div class="label">NEO-TOKYO</div>
      <div class="value">{{ biomeNames[biome] || 'SECTOR 0' }}</div>
    </div>
    <div class="hud-box right">
      <div class="label">REP</div>
      <div class="value accent">{{ score }}</div>
    </div>
  </div>

  <div class="dialogue" *ngIf="dialogue">
    <div class="speaker" [class.rival]="dialogue.speaker === 'Rival'">{{ dialogue.speaker }}</div>
    <div class="text">{{ dialogue.text }}</div>
  </div>

  <div class="combat-text">KNOCKOUT!</div>

  <div class="touch-controls">
    <div class="control-zone left">
      <button
        type="button"
        [class.pressed]="inputSnapshot.slide"
        (touchstart)="handleTouchStart('slide')"
        (touchend)="handleTouchEnd('slide')"
      >
        SLIDE
      </button>
      <button
        type="button"
        [class.pressed]="inputSnapshot.run"
        (touchstart)="handleTouchStart('run')"
        (touchend)="handleTouchEnd('run')"
      >
        DASH
      </button>
    </div>
    <div class="control-zone right">
      <button
        type="button"
        [class.pressed]="inputSnapshot.attack"
        (touchstart)="handleTouchStart('attack')"
        (touchend)="handleTouchEnd('attack')"
      >
        ATK
      </button>
      <button
        type="button"
        [class.pressed]="inputSnapshot.jump"
        (touchstart)="handleTouchStart('jump')"
        (touchend)="handleTouchEnd('jump')"
      >
        JUMP
      </button>
    </div>
  </div>
</div>

// src/components/react/ui/GameHUD.tsx
import { Haptics, ImpactStyle } from '@capacitor/haptics';
import type { FC } from 'react';
import type { InputState } from '@/types/game';
import styles from './GameHUD.module.css';

interface GameHUDProps {
  score: number;
  biome: number;
  inputState: InputState;
  onInput: (key: keyof InputState, value: boolean) => void;
}

const BIOME_NAMES = ['SHIBUYA', 'ROPPONGI', 'AKIHABARA', 'SHINJUKU'];

export const GameHUD: FC<GameHUDProps> = ({ score, biome, inputState, onInput }) => {
  const handleTouchStart = (key: keyof InputState) => {
    onInput(key, true);
    Haptics.impact({ style: ImpactStyle.Light }).catch(() => {});
  };

  const handleTouchEnd = (key: keyof InputState) => {
    onInput(key, false);
  };

  return (
    <div className={styles.hudContainer}>
      {/* Top HUD */}
      <div className={styles.topBar}>
        <div className={styles.hudBox}>
          <div className={styles.hudLabel}>NEO-TOKYO</div>
          <div className={styles.hudVal}>{BIOME_NAMES[biome] || 'SECTOR 0'}</div>
        </div>
        <div style={{ display: 'flex', gap: '2vmin' }}>
          <div className={styles.hudBox} style={{ textAlign: 'right' }}>
            <div className={styles.hudLabel}>REP</div>
            <div className={styles.hudVal} style={{ color: '#0ff' }}>
              {score}
            </div>
          </div>
        </div>
      </div>

      {/* Combat Text */}
      <div
        id="combat-text"
        style={{
          position: 'absolute',
          top: '30%',
          width: '100%',
          textAlign: 'center',
          fontSize: '8vmin',
          fontWeight: 900,
          color: '#fff',
          textShadow: '0.5vmin 0.5vmin 0 #f00',
          fontStyle: 'italic',
          opacity: 0,
          transform: 'scale(0.5) skewX(-20deg)',
          transition: 'transform 0.1s',
          pointerEvents: 'none',
        }}
      >
        KNOCKOUT!
      </div>

      {/* Touch Controls */}
      <div className={styles.touchControls}>
        {/* Left Control Zone */}
        <div
          className={styles.controlZone}
          style={{ alignItems: 'flex-end', paddingLeft: '4vmin' }}
        >
          <button
            type="button"
            className={`${styles.touchBtn} ${styles.btnSlide} ${
              inputState.slide ? styles.touchBtnPressed : ''
            }`}
            onTouchStart={(e) => {
              e.preventDefault();
              handleTouchStart('slide');
            }}
            onTouchEnd={(e) => {
              e.preventDefault();
              handleTouchEnd('slide');
            }}
          >
            SLIDE
          </button>
          <button
            type="button"
            className={`${styles.touchBtn} ${styles.btnRun} ${
              inputState.run ? styles.touchBtnPressed : ''
            }`}
            style={{ marginBottom: '8vmin' }}
            onTouchStart={(e) => {
              e.preventDefault();
              handleTouchStart('run');
            }}
            onTouchEnd={(e) => {
              e.preventDefault();
              handleTouchEnd('run');
            }}
          >
            DASH
          </button>
        </div>

        {/* Right Control Zone */}
        <div
          className={styles.controlZone}
          style={{ alignItems: 'flex-end', paddingRight: '4vmin' }}
        >
          <button
            type="button"
            className={`${styles.touchBtn} ${styles.btnAttack} ${
              inputState.attack ? styles.touchBtnPressed : ''
            }`}
            style={{ marginBottom: '8vmin' }}
            onTouchStart={(e) => {
              e.preventDefault();
              handleTouchStart('attack');
            }}
            onTouchEnd={(e) => {
              e.preventDefault();
              handleTouchEnd('attack');
            }}
          >
            ATK
          </button>
          <button
            type="button"
            className={`${styles.touchBtn} ${styles.btnJump} ${
              inputState.jump ? styles.touchBtnPressed : ''
            }`}
            onTouchStart={(e) => {
              e.preventDefault();
              handleTouchStart('jump');
            }}
            onTouchEnd={(e) => {
              e.preventDefault();
              handleTouchEnd('jump');
            }}
          >
            JUMP
          </button>
        </div>
      </div>
    </div>
  );
};
