// packages/game/src/components/react/ui/CombatArena.tsx
import type { CombatAction } from '@neo-tokyo/core';
import { useCombatStore } from '@neo-tokyo/core';
import { useEffect, useState } from 'react';

export function CombatArena() {
  const { inCombat, phase, player, enemies, combatLog, playerAction, enemyTurn, endCombat } =
    useCombatStore();

  const [selectedTargetId, setSelectedTargetId] = useState<string | null>(null);
  const [showVictory, setShowVictory] = useState(false);
  const [showDefeat, setShowDefeat] = useState(false);

  // Auto-select first enemy
  useEffect(() => {
    if (enemies.length > 0 && !selectedTargetId) {
      setSelectedTargetId(enemies[0].id);
    }
  }, [enemies, selectedTargetId]);

  // Auto-execute enemy turn after player action
  useEffect(() => {
    if (phase === 'enemy_turn') {
      const timer = setTimeout(() => {
        enemyTurn();
      }, 1000);
      return () => clearTimeout(timer);
    }
  }, [phase, enemyTurn]);

  // Show victory/defeat screens
  useEffect(() => {
    if (phase === 'victory') {
      setShowVictory(true);
    } else if (phase === 'defeat') {
      setShowDefeat(true);
    }
  }, [phase]);

  if (!inCombat || !player) return null;

  const handleAction = (actionType: 'attack' | 'defend') => {
    if (phase !== 'player_turn' || !selectedTargetId) return;

    const action: CombatAction = { type: actionType };
    playerAction(action, selectedTargetId);
  };

  const handleVictoryContinue = () => {
    setShowVictory(false);
    endCombat();
  };

  const handleDefeatReload = () => {
    setShowDefeat(false);
    endCombat();
    // TODO: Trigger reload from save
  };

  // Get latest combat log entry
  const latestLog = combatLog.length > 0 ? combatLog[combatLog.length - 1] : null;

  return (
    <div
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        backgroundColor: 'rgba(0, 0, 0, 0.95)',
        zIndex: 1000,
        fontFamily: '"M PLUS 1", sans-serif',
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      {/* Victory Screen */}
      {showVictory && (
        <div
          style={{
            position: 'absolute',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            backgroundColor: 'rgba(16, 185, 129, 0.2)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 2000,
          }}
        >
          <div
            style={{
              backgroundColor: 'rgba(4, 4, 6, 0.98)',
              border: '2px solid #10b981',
              borderRadius: '12px',
              padding: '40px',
              textAlign: 'center',
              maxWidth: '400px',
            }}
          >
            <div style={{ fontSize: '64px', marginBottom: '20px' }}>🏆</div>
            <h2 style={{ fontSize: '32px', color: '#10b981', margin: '0 0 20px 0' }}>VICTORY!</h2>
            <button
              type="button"
              onClick={handleVictoryContinue}
              style={{
                backgroundColor: '#10b981',
                border: 'none',
                borderRadius: '8px',
                color: '#ffffff',
                padding: '14px 28px',
                fontSize: '16px',
                fontWeight: 'bold',
                cursor: 'pointer',
                fontFamily: 'inherit',
              }}
            >
              Continue
            </button>
          </div>
        </div>
      )}

      {/* Defeat Screen */}
      {showDefeat && (
        <div
          style={{
            position: 'absolute',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            backgroundColor: 'rgba(239, 68, 68, 0.2)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 2000,
          }}
        >
          <div
            style={{
              backgroundColor: 'rgba(4, 4, 6, 0.98)',
              border: '2px solid #ef4444',
              borderRadius: '12px',
              padding: '40px',
              textAlign: 'center',
              maxWidth: '400px',
            }}
          >
            <div style={{ fontSize: '64px', marginBottom: '20px' }}>💀</div>
            <h2 style={{ fontSize: '32px', color: '#ef4444', margin: '0 0 20px 0' }}>DEFEATED</h2>
            <button
              type="button"
              onClick={handleDefeatReload}
              style={{
                backgroundColor: '#ef4444',
                border: 'none',
                borderRadius: '8px',
                color: '#ffffff',
                padding: '14px 28px',
                fontSize: '16px',
                fontWeight: 'bold',
                cursor: 'pointer',
                fontFamily: 'inherit',
              }}
            >
              Reload Save
            </button>
          </div>
        </div>
      )}

      {/* Combat Header */}
      <div
        style={{
          padding: '20px',
          borderBottom: '1px solid #334155',
          backgroundColor: 'rgba(15, 23, 42, 0.8)',
        }}
      >
        <div style={{ fontSize: '12px', color: '#64748b', marginBottom: '4px' }}>
          TURN {useCombatStore.getState().turn}
        </div>
        <div style={{ fontSize: '18px', color: '#0ea5e9', fontWeight: 'bold' }}>
          {phase === 'player_turn' ? 'Your Turn' : phase === 'enemy_turn' ? 'Enemy Turn' : 'Combat'}
        </div>
      </div>

      {/* Combat Area */}
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', padding: '20px' }}>
        {/* Player Section */}
        <div style={{ marginBottom: '30px' }}>
          <div style={{ fontSize: '12px', color: '#64748b', marginBottom: '10px' }}>PLAYER</div>
          <div
            style={{
              backgroundColor: 'rgba(14, 165, 233, 0.1)',
              border: '2px solid #0ea5e9',
              borderRadius: '8px',
              padding: '16px',
            }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '10px' }}>
              <span style={{ fontSize: '16px', color: '#e2e8f0', fontWeight: 'bold' }}>
                {player.name}
              </span>
              <span style={{ fontSize: '14px', color: '#94a3b8' }}>
                {player.currentHP} / {player.maxHP} HP
              </span>
            </div>
            <div
              style={{
                width: '100%',
                height: '8px',
                backgroundColor: '#334155',
                borderRadius: '4px',
                overflow: 'hidden',
              }}
            >
              <div
                style={{
                  width: `${(player.currentHP / player.maxHP) * 100}%`,
                  height: '100%',
                  backgroundColor: '#0ea5e9',
                  transition: 'width 0.3s',
                }}
              />
            </div>
          </div>
        </div>

        {/* Enemies Section */}
        <div style={{ marginBottom: '30px' }}>
          <div style={{ fontSize: '12px', color: '#64748b', marginBottom: '10px' }}>ENEMIES</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {enemies.map((enemy) => (
              <button
                type="button"
                key={enemy.id}
                onClick={() => setSelectedTargetId(enemy.id)}
                style={{
                  backgroundColor:
                    selectedTargetId === enemy.id
                      ? 'rgba(239, 68, 68, 0.2)'
                      : 'rgba(239, 68, 68, 0.1)',
                  border: '2px solid',
                  borderColor: selectedTargetId === enemy.id ? '#ef4444' : '#7f1d1d',
                  borderRadius: '8px',
                  padding: '16px',
                  cursor: 'pointer',
                  fontFamily: 'inherit',
                  textAlign: 'left',
                }}
              >
                <div
                  style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '10px' }}
                >
                  <span style={{ fontSize: '16px', color: '#e2e8f0', fontWeight: 'bold' }}>
                    {enemy.name}
                  </span>
                  <span style={{ fontSize: '14px', color: '#94a3b8' }}>
                    {enemy.currentHP} / {enemy.maxHP} HP
                  </span>
                </div>
                <div
                  style={{
                    width: '100%',
                    height: '8px',
                    backgroundColor: '#334155',
                    borderRadius: '4px',
                    overflow: 'hidden',
                  }}
                >
                  <div
                    style={{
                      width: `${(enemy.currentHP / enemy.maxHP) * 100}%`,
                      height: '100%',
                      backgroundColor: '#ef4444',
                      transition: 'width 0.3s',
                    }}
                  />
                </div>
              </button>
            ))}
          </div>
        </div>

        {/* Combat Log */}
        {latestLog && (
          <div
            style={{
              backgroundColor: 'rgba(15, 23, 42, 0.6)',
              border: '1px solid #334155',
              borderRadius: '8px',
              padding: '12px',
              marginBottom: '20px',
            }}
          >
            <div style={{ fontSize: '14px', color: '#cbd5e1' }}>
              {latestLog.hit ? (
                <>
                  <span style={{ color: '#0ea5e9', fontWeight: 'bold' }}>
                    {latestLog.attackerName}
                  </span>{' '}
                  attacks{' '}
                  <span style={{ color: '#ef4444', fontWeight: 'bold' }}>
                    {latestLog.defenderName}
                  </span>{' '}
                  for{' '}
                  <span
                    style={{
                      color: latestLog.critical ? '#f59e0b' : '#e2e8f0',
                      fontWeight: 'bold',
                    }}
                  >
                    {latestLog.damage}
                  </span>{' '}
                  damage{latestLog.critical && ' (CRITICAL!)'}
                </>
              ) : (
                <>
                  <span style={{ color: '#0ea5e9', fontWeight: 'bold' }}>
                    {latestLog.attackerName}
                  </span>
                  's attack missed!
                </>
              )}
            </div>
          </div>
        )}
      </div>

      {/* Action Buttons */}
      <div
        style={{
          padding: '20px',
          borderTop: '1px solid #334155',
          backgroundColor: 'rgba(15, 23, 42, 0.8)',
          display: 'flex',
          gap: '12px',
        }}
      >
        <button
          type="button"
          onClick={() => handleAction('attack')}
          disabled={phase !== 'player_turn'}
          style={{
            flex: 1,
            backgroundColor: phase === 'player_turn' ? '#ef4444' : '#334155',
            border: 'none',
            borderRadius: '8px',
            color: '#ffffff',
            padding: '16px',
            fontSize: '16px',
            fontWeight: 'bold',
            cursor: phase === 'player_turn' ? 'pointer' : 'not-allowed',
            fontFamily: 'inherit',
            opacity: phase === 'player_turn' ? 1 : 0.5,
          }}
        >
          ⚔️ Attack
        </button>
        <button
          type="button"
          onClick={() => handleAction('defend')}
          disabled={phase !== 'player_turn'}
          style={{
            flex: 1,
            backgroundColor: phase === 'player_turn' ? '#3b82f6' : '#334155',
            border: 'none',
            borderRadius: '8px',
            color: '#ffffff',
            padding: '16px',
            fontSize: '16px',
            fontWeight: 'bold',
            cursor: phase === 'player_turn' ? 'pointer' : 'not-allowed',
            fontFamily: 'inherit',
            opacity: phase === 'player_turn' ? 1 : 0.5,
          }}
        >
          🛡️ Defend
        </button>
      </div>
    </div>
  );
}

// src/app/ui/combat-arena.component.ts
import { Component, type NgZone, type OnDestroy, type OnInit } from '@angular/core';
import type { CombatAction } from '@neo-tokyo/core';
import { useCombatStore } from '@neo-tokyo/core';
import { SaveSystem } from '../systems/save-system';

type CombatStoreState = ReturnType<typeof useCombatStore.getState>;

type CombatPhase = CombatStoreState['phase'];

type CombatLogEntry = CombatStoreState['combatLog'][number];

type Combatant = NonNullable<CombatStoreState['player']>;

type EnemyCombatant = CombatStoreState['enemies'][number];

@Component({
  selector: 'app-combat-arena',
  templateUrl: './combat-arena.component.html',
  styleUrls: ['./combat-arena.component.scss'],
})
export class CombatArenaComponent implements OnInit, OnDestroy {
  inCombat = false;
  phase: CombatPhase = 'idle';
  turn = 0;
  player: Combatant | null = null;
  enemies: EnemyCombatant[] = [];
  combatLog: CombatLogEntry[] = [];

  selectedTargetId: string | null = null;
  showVictory = false;
  showDefeat = false;

  private unsubscribe: (() => void) | null = null;
  private enemyTurnTimeout: number | null = null;

  constructor(private readonly zone: NgZone) {}

  ngOnInit(): void {
    this.syncState(useCombatStore.getState());

    this.unsubscribe = useCombatStore.subscribe((state) => {
      this.zone.run(() => {
        this.syncState(state);
      });
    });
  }

  ngOnDestroy(): void {
    this.unsubscribe?.();
    this.clearEnemyTurnTimeout();
  }

  get latestLog(): CombatLogEntry | null {
    return this.combatLog.length > 0 ? this.combatLog[this.combatLog.length - 1] : null;
  }

  handleAction(actionType: 'attack' | 'defend'): void {
    if (this.phase !== 'player_turn' || !this.selectedTargetId) return;

    const action: CombatAction = { type: actionType };
    useCombatStore.getState().playerAction(action, this.selectedTargetId);
  }

  handleVictoryContinue(): void {
    this.showVictory = false;
    useCombatStore.getState().endCombat();
  }

  handleDefeatReload(): void {
    this.showDefeat = false;
    SaveSystem.load(0);
    useCombatStore.getState().endCombat();
  }

  selectTarget(enemyId: string): void {
    this.selectedTargetId = enemyId;
  }

  private syncState(state: CombatStoreState): void {
    this.inCombat = state.inCombat;
    this.phase = state.phase;
    this.turn = state.turn;
    this.player = state.player;
    this.enemies = state.enemies;
    this.combatLog = state.combatLog;

    if (this.enemies.length > 0) {
      const targetExists = this.selectedTargetId
        ? this.enemies.some((enemy) => enemy.id === this.selectedTargetId)
        : false;
      if (!targetExists) {
        this.selectedTargetId = this.enemies[0].id;
      }
    } else {
      this.selectedTargetId = null;
    }

    this.showVictory = this.phase === 'victory';
    this.showDefeat = this.phase === 'defeat';

    if (this.phase === 'enemy_turn' && this.inCombat) {
      this.scheduleEnemyTurn();
    } else {
      this.clearEnemyTurnTimeout();
    }
  }

  private scheduleEnemyTurn(): void {
    if (this.enemyTurnTimeout) return;
    this.enemyTurnTimeout = window.setTimeout(() => {
      useCombatStore.getState().enemyTurn();
      this.enemyTurnTimeout = null;
    }, 900);
  }

  private clearEnemyTurnTimeout(): void {
    if (this.enemyTurnTimeout) {
      window.clearTimeout(this.enemyTurnTimeout);
      this.enemyTurnTimeout = null;
    }
  }
}

<div class="combat-arena" *ngIf="inCombat && player">
  <div class="combat-overlay" *ngIf="showVictory">
    <div class="combat-modal success">
      <div class="combat-icon">🏆</div>
      <h2>Victory</h2>
      <p>Rewards are being tallied.</p>
      <button type="button" (click)="handleVictoryContinue()">Continue</button>
    </div>
  </div>

  <div class="combat-overlay" *ngIf="showDefeat">
    <div class="combat-modal danger">
      <div class="combat-icon">💀</div>
      <h2>Defeated</h2>
      <p>Return to the last autosave.</p>
      <button type="button" (click)="handleDefeatReload()">Reload Save</button>
    </div>
  </div>

  <header class="combat-header">
    <div class="turn-label">Turn {{ turn }}</div>
    <div class="phase-label">
      {{ phase === 'player_turn' ? 'Your Turn' : phase === 'enemy_turn' ? 'Enemy Turn' : 'Combat' }}
    </div>
  </header>

  <section class="combat-body">
    <div class="combat-panel">
      <div class="panel-title">Player</div>
      <div class="combat-card player">
        <div class="card-row">
          <span class="card-name">{{ player?.name }}</span>
          <span class="card-hp">{{ player?.currentHP }} / {{ player?.maxHP }} HP</span>
        </div>
        <div class="hp-bar">
          <div
            class="hp-fill"
            [style.width.%]="player ? (player.currentHP / player.maxHP) * 100 : 0"
          ></div>
        </div>
      </div>
    </div>

    <div class="combat-panel">
      <div class="panel-title">Enemies</div>
      <div class="enemy-list">
        <button
          type="button"
          class="combat-card enemy"
          *ngFor="let enemy of enemies"
          [class.selected]="enemy.id === selectedTargetId"
          (click)="selectTarget(enemy.id)"
        >
          <div class="card-row">
            <span class="card-name">{{ enemy.name }}</span>
            <span class="card-hp">{{ enemy.currentHP }} / {{ enemy.maxHP }} HP</span>
          </div>
          <div class="hp-bar">
            <div
              class="hp-fill enemy"
              [style.width.%]="(enemy.currentHP / enemy.maxHP) * 100"
            ></div>
          </div>
        </button>
      </div>
    </div>

    <div class="combat-panel" *ngIf="latestLog">
      <div class="panel-title">Combat Log</div>
      <div class="combat-log">
        <ng-container *ngIf="latestLog?.hit; else missTemplate">
          <span class="log-attacker">{{ latestLog?.attackerName }}</span>
          attacks
          <span class="log-defender">{{ latestLog?.defenderName }}</span>
          for
          <span class="log-damage" [class.critical]="latestLog?.critical">{{ latestLog?.damage }}</span>
          damage{{ latestLog?.critical ? ' (CRITICAL)' : '' }}
        </ng-container>
        <ng-template #missTemplate>
          <span class="log-attacker">{{ latestLog?.attackerName }}</span>
          's attack missed.
        </ng-template>
      </div>
    </div>
  </section>

  <footer class="combat-actions">
    <button
      type="button"
      class="action-btn attack"
      [disabled]="phase !== 'player_turn'"
      (click)="handleAction('attack')"
    >
      Attack
    </button>
    <button
      type="button"
      class="action-btn defend"
      [disabled]="phase !== 'player_turn'"
      (click)="handleAction('defend')"
    >
      Defend
    </button>
  </footer>
</div>
